# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import snuchoice.choice.models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=snuchoice.choice.models.Candidate.upload_to_photo),
        ),
        migrations.AlterField(
            model_name='party',
            name='book',
            field=models.FileField(blank=True, null=True, upload_to=snuchoice.choice.models.Party.upload_to_book),
        ),
        migrations.AlterField(
            model_name='party',
            name='leaflet',
            field=models.FileField(blank=True, null=True, upload_to=snuchoice.choice.models.Party.upload_to_leaflet),
        ),
        migrations.AlterField(
            model_name='party',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=snuchoice.choice.models.Party.upload_to_logo),
        ),
        migrations.AlterField(
            model_name='press',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=snuchoice.choice.models.Press.upload_to_logo),
        ),
    ]
